import type { DetailGoal, ListGoal, SearchGoal } from "./types";

export const MAIN_SERVER_URL = "http://127.0.0.1:3010";
export const COOP_SERVER_URL = "http://127.0.0.1:3011";
export const GUEST_SERVER_URL = "http://127.0.0.1:3012";

export const LIST_GOALS: ListGoal[] = [
    {
        trigger: "Jobs",
        route: "/jobs",
        title: "Jobs",
        operationName: "ListJobs",
        responseKey: "Jobs",
        expectedVariables: { limit: 20, page: 1 },
        expectedResultTitle: "Dockmaster",
    },
    {
        trigger: "Market",
        route: "/products-services",
        title: "Products / Services",
        operationName: "ListProducts",
        responseKey: "Products",
        expectedVariables: { limit: 20, page: 1 },
        expectedResultTitle: "Solar Widget",
    },
    {
        trigger: "Companies",
        route: "/companies",
        title: "Companies",
        operationName: "ListCompanies",
        responseKey: "Companies",
        expectedVariables: { limit: 20, page: 1 },
        expectedResultTitle: "Harbor Labs",
    },
    {
        trigger: "Ventures",
        route: "/ventures",
        title: "Ventures",
        operationName: "ListStartups",
        responseKey: "Startups",
        expectedVariables: { limit: 20, page: 1 },
        expectedResultTitle: "Sky Relay",
    },
    {
        trigger: "Tribes",
        route: "/tribes",
        title: "Tribes",
        operationName: "ListIdentities",
        responseKey: "Identities",
        expectedVariables: { limit: 20, page: 1 },
        expectedResultTitle: "Nova Rivers",
    },
];

export const SYNDICATION_LIST_GOAL = {
    clickLabel: "Manage endpoints",
    route: "/syndication",
    title: "Syndication",
    operationName: "ListPublishedSyndicationUrls",
    responseKey: "Syndications",
    expectedVariables: {},
    expectedResultTitle: "Main",
} as const;

export const DETAIL_HOME_GOALS: DetailGoal[] = [
    {
        selector: ".SplashEntityCard__itemLink",
        label: "Dockmaster",
        route: "/jobs/job-dockmaster",
        title: "Dockmaster",
        query: {
            operationName: "JobById",
            responseKey: "Job",
            expectedId: "job-dockmaster",
            expectedVariables: { id: "job-dockmaster" },
        },
    },
    {
        selector: ".SplashEntityCard__itemLink",
        label: "Solar Widget",
        route: "/products-services/product-solar-widget",
        title: "Solar Widget",
        query: {
            operationName: "ProductById",
            responseKey: "Product",
            expectedId: "product-solar-widget",
            expectedVariables: { id: "product-solar-widget" },
        },
    },
    {
        selector: ".SplashEntityCard__itemLink",
        label: "Harbor Labs",
        route: "/companies/company-harbor-labs",
        title: "Harbor Labs",
        query: {
            operationName: "CompanyById",
            responseKey: "Company",
            expectedId: "company-harbor-labs",
            expectedVariables: { id: "company-harbor-labs" },
        },
    },
    {
        selector: ".SplashEntityCard__itemLink",
        label: "Sky Relay",
        route: "/ventures/startup-sky-relay",
        title: "Sky Relay",
        query: {
            operationName: "StartupById",
            responseKey: "Startup",
            expectedId: "startup-sky-relay",
            expectedVariables: { id: "startup-sky-relay" },
        },
    },
    {
        selector: ".SplashPage__identityHeadingLink",
        label: "Nova Rivers",
        route: "/tribes/identity-nova",
        title: "Nova Rivers",
        query: {
            operationName: "IdentityById",
            responseKey: "Identity",
            expectedId: "identity-nova",
            expectedVariables: { id: "identity-nova" },
        },
    },
    {
        selector: ".SplashPage__syndicationCardTitleLink",
        label: "Main",
        route: `/syndication/${encodeURIComponent(MAIN_SERVER_URL)}`,
        title: "Main",
    },
];

export const SEARCH_GOALS: SearchGoal[] = [
    {
        scopeLabel: "Jobs",
        searchTitle: "Job search",
        term: "Dockmaster",
        resultLabel: "Dockmaster",
        route: "/jobs/job-dockmaster",
        title: "Dockmaster",
        searchOperationName: "SearchJobs",
        detailOperationName: "JobById",
        expectedId: "job-dockmaster",
        responseKey: "Job",
        searchExpectedTitle: "Dockmaster",
        detailExpectedVariables: { id: "job-dockmaster" },
    },
    {
        scopeLabel: "Products / Services",
        searchTitle: "Product / Service search",
        term: "Solar Widget",
        resultLabel: "Solar Widget",
        route: "/products-services/product-solar-widget",
        title: "Solar Widget",
        searchOperationName: "SearchProducts",
        detailOperationName: "ProductById",
        expectedId: "product-solar-widget",
        responseKey: "Product",
        searchExpectedTitle: "Solar Widget",
        detailExpectedVariables: { id: "product-solar-widget" },
    },
    {
        scopeLabel: "Companies",
        searchTitle: "Company search",
        term: "Harbor Labs",
        resultLabel: "Harbor Labs",
        route: "/companies/company-harbor-labs",
        title: "Harbor Labs",
        searchOperationName: "SearchCompanies",
        detailOperationName: "CompanyById",
        expectedId: "company-harbor-labs",
        responseKey: "Company",
        searchExpectedTitle: "Harbor Labs",
        detailExpectedVariables: { id: "company-harbor-labs" },
    },
    {
        scopeLabel: "Tribes",
        searchTitle: "Tribe search",
        term: "Nova Rivers",
        resultLabel: "Nova Rivers",
        route: "/tribes/identity-nova",
        title: "Nova Rivers",
        searchOperationName: "SearchIdentities",
        detailOperationName: "IdentityById",
        expectedId: "identity-nova",
        responseKey: "Identity",
        searchExpectedTitle: "Nova Rivers",
        detailExpectedVariables: { id: "identity-nova" },
    },
    {
        scopeLabel: "Ventures",
        searchTitle: "Startup search",
        term: "Sky Relay",
        resultLabel: "Sky Relay",
        route: "/ventures/startup-sky-relay",
        title: "Sky Relay",
        searchOperationName: "SearchStartups",
        detailOperationName: "StartupById",
        expectedId: "startup-sky-relay",
        responseKey: "Startup",
        searchExpectedTitle: "Sky Relay",
        detailExpectedVariables: { id: "startup-sky-relay" },
    },
];

export const DEEP_DIVE_ROUTES = {
    home: "/",
    companies: "/companies",
    company: "/companies/company-harbor-labs",
    job: "/jobs/job-dockmaster",
    inactiveJob: "/jobs/job-harbor-watch",
    venture: "/ventures/startup-sky-relay",
    identity: "/tribes/identity-nova",
} as const;
