query CartBySecret($secret: String!) {
  Carts(
    draft: false
    limit: 1
    sort: "-updatedAt"
    where: { secret: { equals: $secret } }
  ) {
    docs {
      id
      secret
      status
      currency
      subtotal
      createdAt
      updatedAt
      purchasedAt
      customer {
        id
        name
        email
      }
      items {
        id
        quantity
        product {
          id
          serverURL
          name
          description
          orderable
          cryptoAddresses {
          chain
          address
        }
          inventory
          url
          priceInUSD
          priceInUSDEnabled
          image {
            id
            url
            alt
            filename
            width
            height
            mimeType
          }
          company {
            id
            serverURL
            name
            description
            cryptoAddresses {
          chain
          address
        }
            identity {
              id
              serverURL
              name
              description
            }
          }
        }
        variant {
          id
          title
          inventory
          priceInUSD
          priceInUSDEnabled
          options {
            id
            label
            value
            variantType {
              id
              name
            }
          }
        }
      }
    }
    totalDocs
  }
}
