mutation CreateCart($data: mutationCartInput!, $draft: Boolean!) {
    createCart(data: $data, draft: $draft) {
        id
        secret
        status
        currency
        subtotal
        createdAt
        updatedAt
        purchasedAt
        customer {
            id
            name
            email
        }
        items {
            id
            quantity
            product {
                id
                serverURL
                name
                cryptoAddresses {
                    chain
                    address
                }
            }
            variant {
                id
                title
            }
        }
    }
}
