query ListCompaniesByCreator(
    $userId: JSON,
    $page: Int = 1,
    $limit: Int = 100,
    $sort: String = "-contentRankScore",
    $draft: Boolean = false,
) {
    Companies(draft: $draft, page: $page, limit: $limit, sort: $sort, where: { createdBy: { equals: $userId } }) {
        docs {
            id
            isSubscribed
            serverURL
            name
            verification
            isPrivate
            likeCount
            cryptoAddresses {
                chain
                address
            }
            image {
                id
                url
                alt
                filename
                width
                height
                mimeType
            }
            _status
        }
        totalDocs
    }
}
