query ListCompaniesByIdentity($identityId: JSON!, $page: Int = 1, $limit: Int = 20, $sort: String = "-contentRankScore") {
    Companies(
        draft: false
        where: { AND: [{ identity: { equals: $identityId } }, { _status: { equals: published } }, { isPrivate: { equals: false } }] }
        page: $page
        limit: $limit
        sort: $sort
    ) {
        docs {
            id
            isSubscribed
            serverURL
            name
            verification
            isPrivate
            description
            hasLiked
            likeCount
            cryptoAddresses {
                chain
                address
            }
            website
            phone
            email
            allowedIdentities {
                id
                serverURL
                name
                description
            }
            disallowedIdentities {
                id
                serverURL
                name
                description
            }
            identity {
                id
                serverURL
                name
                description
                image {
                    id
                    url
                    alt
                    filename
                    width
                    height
                    mimeType
                }
            }
            image {
                id
                url
                alt
                filename
                width
                height
                mimeType
            }
        }
        totalDocs
        limit
        totalPages
        page
        hasPrevPage
        hasNextPage
        prevPage
        nextPage
    }
}
