query CompanyById($id: String!) {
  Company(id: $id) {
    id
    serverURL
    name
    _status
    description
    cryptoAddresses {
      ethereum
      tron
      solana
    }
    website
    phone
    email
    allowedIdentities {
      id
      serverURL
      name
      description
    }
    disallowedIdentities {
      id
      serverURL
      name
      description
    }
    createdBy {
      id
    }
    identity {
      id
      serverURL
      name
      description
      website
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
    }
    image {
      id
      url
      alt
      filename
      width
      height
      mimeType
    }
  }
}
