query ListIdentities($page: Int = 1, $limit: Int = 20) {
    Identities(draft: false, page: $page, limit: $limit) {
        docs {
            id
            isSubscribed
            serverURL
            name
            description
            website
            likeCount
            itemCount
            image {
                id
                url
                alt
                filename
                width
                height
                mimeType
            }
        }
        totalDocs
        limit
        totalPages
        page
        hasPrevPage
        hasNextPage
        prevPage
        nextPage
    }
}
