query ListProductsByIdentity($identityId: String!, $limit: Int = 50, $page: Int = 1) {
  Products(
    where: { companyIdentityId: { equals: $identityId } }
    sort: "-createdAt"
    limit: $limit
    page: $page
  ) {
    docs {
      id
      serverURL
      name
      cryptoAddresses {
          chain
          address
        }
      orderable
      url
      companyIdentityId
      priceInUSDEnabled
      priceInUSD
      priceInETH
      priceInSOL
      priceInTRX
      company {
        id
        serverURL
        name
        cryptoAddresses {
          chain
          address
        }
        image {
          id
          url
        }
      }
      image {
        id
        url
      }
      _status
      createdAt
    }
    totalDocs
    hasNextPage
    nextPage
  }
}
