query ListJobsByIdentity($identityId: String!, $limit: Int = 50, $page: Int = 1) {
    Jobs(
        draft: false
        where: { AND: [{ companyIdentityId: { equals: $identityId } }, { _status: { equals: published } }] }
        limit: $limit
        page: $page
    ) {
        docs {
            id
            isSubscribed
            serverURL
            title
            companyIdentityId
            company {
                id
                serverURL
                name
                cryptoAddresses {
                    chain
                    address
                }
                image {
                    id
                    url
                }
            }
            location
            employmentType
            salaryRange {
                min
                max
                currency
            }
            image {
                id
                url
            }
            postedAt
            _status
        }
        totalDocs
        hasNextPage
        nextPage
    }
}
