query ListCommentsByTarget($targetId: String!, $relationTo: String!, $limit: Int = 50, $page: Int = 1) {
    Comments(
        draft: false
        where: {
            AND: [
                { replyPostRelationTo: { equals: $relationTo } }
                { replyPostValue: { equals: $targetId } }
                { replyComment: { exists: false } }
            ]
        }
        sort: "createdAt"
        limit: $limit
        page: $page
    ) {
        docs {
            id
            content
            serverUrl
            createdBy {
                id
                name
                email
            }
            company {
                id
                serverURL
                name
                image {
                    id
                    url
                    alt
                    filename
                    width
                    height
                    mimeType
                }
            }
            replyPostRelationTo
            replyPostValue
            createdAt
            updatedAt
            likeCount
            hasLiked
            replyCount
            replyPost {
                relationTo
            }
        }
        totalDocs
        hasNextPage
        nextPage
    }
}
