query ListCommentsByTarget(
  $targetId: JSON!
  $relationTo: Comment_replyPost_Relation_RelationTo!
  $limit: Int = 50
) {
  Comments(
    where: {
      AND: [
        { replyPost: { relationTo: $relationTo } }
        { replyPost: { value: { equals: $targetId } } }
      ]
    }
    sort: "createdAt"
    limit: $limit
  ) {
    docs {
      id
      content
      createdBy {
        id
        name
        email
      }
      anonymousHash
      createdAt
      updatedAt
      replyComment {
        id
      }
      replyPost {
        relationTo
      }
    }
    totalDocs
    hasNextPage
    nextPage
  }
}
