query ListProductsByIdentity($identityId: String!, $limit: Int = 50, $page: Int = 1, $sort: String = "-contentRankScore") {
    Products(
        draft: false
        where: { AND: [{ companyIdentityId: { equals: $identityId } }, { _status: { equals: published } }] }
        limit: $limit
        page: $page
        sort: $sort
    ) {
        docs {
            id
            isSubscribed
            serverURL
            name
            description
            inventory
            hasLiked
            likeCount
            cryptoAddresses {
                chain
                address
            }
            orderable
            url
            companyIdentityId
            priceInUSDEnabled
            priceInUSD
            priceInETH
            priceInSOL
            priceInTRX
            company {
                id
                serverURL
                name
                cryptoAddresses {
                    chain
                    address
                }
                identity {
                    id
                    serverURL
                    name
                    description
                }
                image {
                    id
                    url
                }
            }
            image {
                id
                url
            }
            _status
            createdAt
        }
        totalDocs
        hasNextPage
        nextPage
    }
}
