mutation UpdateOrder($orderId: String!, $data: mutationOrderUpdateInput!, $draft: Boolean!) {
    updateOrder(id: $orderId, data: $data, draft: $draft) {
        id
        status
        payerAddress
        customer {
            id
        }
        transactions {
            id
        }
        cryptoPrices {
            id
            chain
            stablePerNative
            nativePerStable
            expectedNativeAmount
            fetchedAt
        }
        transactionHashes {
            id
            chain
            transactionHash
            product {
                id
            }
        }
        currency
        amount
        customerEmail
        createdAt
        updatedAt
        items {
            id
            quantity
            product {
                id
                serverURL
                name
                priceInETH
                priceInSOL
                priceInTRX
                cryptoAddresses {
                    chain
                    address
                }
                company {
                    id
                    cryptoAddresses {
                        chain
                        address
                    }
                }
            }
            variant {
                id
                title
            }
        }
        shippingAddress {
            title
            firstName
            lastName
            company
            addressLine1
            addressLine2
            city
            postalCode
            state
            country
            phone
        }
    }
}
