mutation UpdateOrder($id: String!, $data: mutationOrderUpdateInput!, $draft: Boolean!) {
  updateOrder(id: $id, data: $data, draft: $draft) {
    id
    status
    payerAddress
    transactionHashes {
      chain
      transactionHash
      id
    }
    currency
    amount
    customerEmail
    createdAt
    updatedAt
    items {
      id
      quantity
      product {
        id
        serverURL
        name
        cryptoAddresses {
          ethereum
          tron
          solana
        }
      }
      variant {
        id
        title
      }
    }
    shippingAddress {
      title
      firstName
      lastName
      company
      addressLine1
      addressLine2
      city
      postalCode
      state
      country
      phone
    }
  }
}
