mutation CreatePostReplyComment(
  $replyToPost: Comment_ReplyPostRelationshipInput!
  $company: String!
  $parentCommentId: String!
  $content: String!
) {
  createComment(data: { content: $content, company: $company, replyPost: $replyToPost, replyComment: $parentCommentId }) {
    id
    content
    company {
      id
      serverURL
      name
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
    }
    replyComment {
      id
    }
    createdBy {
      id
      name
      email
    }
    createdAt
    replyCount
  }
}
