query ListPostComments($postId: String!, $limit: Int = 50, $page: Int = 1) {
  Comments(
    draft: false
    where: {
      AND: [
        { replyPostRelationTo: { equals: "posts" } }
        { replyPostValue: { equals: $postId } }
        { replyComment: { exists: false } }
      ]
    }
    sort: "createdAt"
    limit: $limit
    page: $page
  ) {
    docs {
      id
      content
      createdBy {
        id
        name
        email
      }
      anonymousHash
      replyPostRelationTo
      replyPostValue
      createdAt
      updatedAt
      likeCount
      hasLiked
      replyPost {
        relationTo
      }
    }
    totalDocs
    hasNextPage
    nextPage
  }
}
