query ListPostCommentReplies($parentCommentId: JSON!, $limit: Int = 100, $page: Int = 1) {
  Comments(draft: false, where: { replyComment: { equals: $parentCommentId } }, sort: "createdAt", limit: $limit, page: $page) {
    docs {
      id
      content
      createdBy {
        id
        name
        email
      }
      anonymousHash
      createdAt
      updatedAt
      likeCount
      hasLiked
      replyComment {
        id
      }
      replyPost {
        relationTo
      }
    }
    totalDocs
    hasNextPage
    nextPage
  }
}
