query SearchPosts($searchTerm: String!, $page: Int = 1, $limit: Int = 20, $sort: String = "-contentRankScore") {
  Searches(
    draft: false
    where: { AND: [{ title: { contains: $searchTerm } }, { doc: { relationTo: posts } }] }
    page: $page
    limit: $limit
    sort: $sort
  ) {
    docs {
      title
      priority
      doc(draft: false) {
        relationTo
        value {
          ... on Post {
            __typename
            id
            title
            slug
            heroImage {
              id
              url
              alt
              filename
              width
              height
              mimeType
            }
            meta {
              description
              image {
                id
                url
                alt
                filename
                width
                height
                mimeType
              }
            }
            categories {
              id
              title
              slug
            }
            hasLiked
            likeCount
          }
        }
      }
    }
    totalDocs
    limit
    totalPages
    page
    hasPrevPage
    hasNextPage
    prevPage
    nextPage
  }
}
