query PostById($id: String!, $draft: Boolean = false) {
  Post(id: $id, draft: $draft) {
    id
    title
    slug
    heroImage {
      id
      url
      alt
      filename
      width
      height
      mimeType
    }
    content
    meta {
      title
      description
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
    }
    company {
      id
      serverURL
      name
      description
      cryptoAddresses {
        chain
        address
      }
      identity {
        id
        serverURL
        name
        description
      }
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
    }
    hasLiked
    likeCount
    publishedAt
    updatedAt
    createdAt
    _status
  }
}
