query ListProductsByCompany($companyId: JSON!, $page: Int = 1, $limit: Int = 20, $sort: String) {
  Products(
    draft: false
    where: { company: { equals: $companyId } }
    page: $page
    limit: $limit
    sort: $sort
  ) {
    docs {
      id
      serverURL
      name
      inventory
      description
      cryptoAddresses {
          chain
          address
        }
      url
      orderable
      properties {
        id
        key
        value
      }
      price {
        amount
        currency
      }
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
      company {
        id
        serverURL
        name
        description
        cryptoAddresses {
          chain
          address
        }
        identity {
          id
          serverURL
          name
          description
        }
      }
    }
    totalDocs
    limit
    totalPages
    page
    hasPrevPage
    hasNextPage
    prevPage
    nextPage
  }
}
