query ProductById($id: String!) {
  Product(id: $id) {
    id
    name
    _status
    description
    url
    properties {
      id
      key
      value
    }
    inventory
    price {
      amount
      currency
    }
    company {
      id
      name
      description
      createdBy {
        id
      }
      identity {
        id
        name
        description
      }
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
    }
    image {
      id
      url
      alt
      filename
      width
      height
      mimeType
    }
  }
}
