mutation UpdateProduct($id: String!, $data: mutationProductUpdateInput!, $draft: Boolean!) {
    updateProduct(id: $id, data: $data, draft: $draft) {
        id
        name
        cryptoAddresses {
            chain
            address
        }
        _status
        properties {
            id
            key
            value
        }
        parameters {
            id
            name
            values {
                id
                key
                name
                default
            }
        }
        relatedProducts {
            id
            name
            serverURL
        }
        image {
            id
            url
        }
    }
}
