mutation UpdateSellerOrderProductFulfilled(
    $fulfilled: Boolean!
    $orderId: String!
    $paymentProofId: String!
) {
    updateSellerOrderProductFulfilled(
        fulfilled: $fulfilled
        orderId: $orderId
        paymentProofId: $paymentProofId
    ) {
        id
        chain
        fulfilled
        rejected
        orderCreatedAt
        orderId
        orderStatus
        payerAddress
        paymentProof {
            chain
            fulfilled
            rejected
            id
            transactionHash
        }
        paymentProofId
        product {
            id
            name
            company {
                id
                name
            }
            createdBy {
                id
            }
            updatedAt
            createdAt
        }
        productId
        quantity
        shippingAddress {
            title
            firstName
            lastName
            company
            addressLine1
            addressLine2
            city
            postalCode
            state
            country
            phone
        }
        transactionHash
    }
}
