query ListStartupsByIdentity($identityId: JSON!, $page: Int = 1, $limit: Int = 20) {
    Startups(
        draft: false
        where: { AND: [{ identity: { equals: $identityId } }, { _status: { equals: published } }] }
        page: $page
        limit: $limit
    ) {
        docs {
            id
            isSubscribed
            title
            description
            hasLiked
            likeCount
            stage
            identity {
                id
                name
            }
            image {
                id
                url
            }
        }
        totalDocs
        hasNextPage
        nextPage
    }
}
