query ListStartupsByIdentity($identityId: JSON!, $page: Int = 1, $limit: Int = 20) {
    Startups(
        draft: false
        where: { AND: [{ identity: { equals: $identityId } }, { _status: { equals: published } }] }
        page: $page
        limit: $limit
    ) {
        docs {
            id
            isSubscribed
            serverURL
            title
            description
            hasLiked
            likeCount
            stage
            lookingFor
            company {
                id
                serverURL
                name
                email
            }
            identity {
                id
                serverURL
                name
                description
                image {
                    id
                    url
                    alt
                    filename
                    width
                    height
                    mimeType
                }
            }
            image {
                id
                url
            }
        }
        totalDocs
        hasNextPage
        nextPage
    }
}
