query ListStartups($page: Int = 1, $limit: Int = 20, $sort: String) {
  Startups(draft: false, page: $page, limit: $limit, sort: $sort) {
    docs {
      id
      serverURL
      title
      description
      stage
      lookingFor
      alreadyHave
      fundsNeeded {
        amount
        currency
      }
      company {
        id
        serverURL
        name
        cryptoAddresses {
          chain
          address
        }
        email
      }
      identity {
        id
        serverURL
        name
        description
        image {
          id
          url
          alt
          filename
          width
          height
          mimeType
        }
      }
      image {
        id
        url
        alt
        filename
        width
        height
        mimeType
      }
      involvedUsers {
        id
        name
        email
      }
    }
    totalDocs
    limit
    totalPages
    page
    hasPrevPage
    hasNextPage
    prevPage
    nextPage
  }
}
