import type { MockCollection } from "./types";
import type {
    FixtureCart,
    FixtureComment,
    FixtureCompany,
    FixtureIdentity,
    FixtureJob,
    FixtureMeUser,
    FixtureMedia,
    FixtureOrder,
    FixturePost,
    FixtureProduct,
    FixtureStartup,
    FixtureSyndication,
    GraphQLFixtureBundle,
} from "./fixtures/types";
import { buildMockImageNode } from "./imageAssets";

const COOP_SYNDICATION_URL = "http://127.0.0.1:3011";

const image = (id: string, alt: string): FixtureMedia => buildMockImageNode(id, alt, id.startsWith("coop-post-") ? "hero" : "avatar");

const collection = <T>(docs: T[]): MockCollection<T> => ({
    docs,
    totalDocs: docs.length,
    limit: docs.length,
    totalPages: 1,
    page: 1,
    hasPrevPage: false,
    hasNextPage: false,
    prevPage: null,
    nextPage: null,
});

const identities = [
    {
        id: "coop-identity-iris",
        name: "Iris Shore",
        description: "Shipping coordinator",
        website: "https://iris.example",
        email: "iris@example.test",
        serverURL: COOP_SYNDICATION_URL,
        image: image("coop-identity-iris", "Iris Shore"),
    },
    {
        id: "coop-identity-luca",
        name: "Luca Vale",
        description: "Community builder",
        website: "https://luca.example",
        email: "luca@example.test",
        serverURL: COOP_SYNDICATION_URL,
        image: image("coop-identity-luca", "Luca Vale"),
    },
    {
        id: "coop-identity-rhea",
        name: "Rhea Moss",
        description: "Operations lead",
        website: "https://rhea.example",
        email: "rhea@example.test",
        serverURL: COOP_SYNDICATION_URL,
        image: image("coop-identity-rhea", "Rhea Moss"),
    },
] satisfies FixtureIdentity[];

const companies = [
    {
        id: "coop-company-helix-harbor",
        name: "Helix Harbor",
        description: "Cooperative logistics and export tools",
        website: "https://helix.example",
        phone: "+1 555 5100",
        email: "hello@helix.example",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: true,
        createdBy: identities[0],
        identity: identities[0],
        allowedIdentities: [identities[0], identities[2]],
        disallowedIdentities: [identities[1]],
        cryptoAddresses: [{ chain: "solana", address: "SoHelix510" }],
        image: image("coop-company-helix-harbor", "Helix Harbor"),
    },
    {
        id: "coop-company-salt-works",
        name: "Salt Works",
        description: "Lightweight design and production",
        website: "https://salt.example",
        phone: "+1 555 5200",
        email: "team@salt.example",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: false,
        createdBy: identities[1],
        identity: identities[1],
        allowedIdentities: [identities[1]],
        disallowedIdentities: [identities[2]],
        cryptoAddresses: [{ chain: "ethereum", address: "0xSalt520" }],
        image: image("coop-company-salt-works", "Salt Works"),
    },
    {
        id: "coop-company-harbor-ether",
        name: "Harbor Ether",
        description: "Co-op vendor with the shared Ethereum address",
        website: "https://harbor-ether.example",
        phone: "+1 555 5300",
        email: "team@harbor-ether.example",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: true,
        createdBy: identities[0],
        identity: identities[0],
        allowedIdentities: [identities[0]],
        disallowedIdentities: [identities[1]],
        cryptoAddresses: [{ chain: "ethereum", address: "0xHarbor111" }],
        image: image("coop-company-harbor-ether", "Harbor Ether"),
    },
] satisfies FixtureCompany[];

const products = [
    {
        id: "coop-product-lighthouse-kit",
        name: "Lighthouse Kit",
        description: "Unlimited navigation hardware",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: true,
        url: "/products/lighthouse-kit",
        inventory: null,
        orderable: true,
        enableVariants: false,
        companyIdentityId: identities[0].id,
        priceInUSDEnabled: true,
        priceInUSD: 64,
        priceInETH: 0.027,
        priceInSOL: 1.1,
        priceInTRX: 141,
        cryptoAddresses: [{ chain: "solana", address: "SoLight620" }],
        variantTypes: [],
        variants: collection([]),
        properties: [{ id: "coop-product-prop-1", key: "finish", value: "matte" }],
        image: image("coop-product-lighthouse-kit", "Lighthouse Kit"),
        company: companies[0],
    },
    {
        id: "coop-product-tide-lamp",
        name: "Tide Lamp",
        description: "Limited batch desk lamp",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: false,
        url: "/products/tide-lamp",
        inventory: 5,
        orderable: true,
        enableVariants: true,
        companyIdentityId: identities[1].id,
        priceInUSDEnabled: true,
        priceInUSD: 99,
        priceInETH: 0.041,
        priceInSOL: 1.7,
        priceInTRX: 208,
        cryptoAddresses: [{ chain: "tron", address: "TTide630" }],
        variantTypes: [{ id: "coop-variant-size", name: "size", label: "Size" }],
        variants: collection([
            {
                id: "coop-tide-lamp-mini",
                title: "Mini",
                inventory: 2,
                priceInUSDEnabled: true,
                priceInUSD: 89,
                options: [
                    {
                        id: "coop-tide-lamp-mini-size",
                        label: "Size",
                        value: "Mini",
                        variantType: { id: "coop-variant-size", name: "size", label: "Size" },
                    },
                ],
            },
        ]),
        properties: [{ id: "coop-product-prop-2", key: "theme", value: "dawn" }],
        image: image("coop-product-tide-lamp", "Tide Lamp"),
        company: companies[1],
    },
    {
        id: "coop-product-harbor-ether-lantern",
        name: "Harbor Ether Lantern",
        description: "Ethereum product from the co-op server",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: false,
        url: "/products/harbor-ether-lantern",
        inventory: 3,
        orderable: true,
        enableVariants: false,
        companyIdentityId: identities[0].id,
        priceInUSDEnabled: true,
        priceInUSD: 38,
        priceInETH: 0.041,
        priceInSOL: 0.9,
        priceInTRX: 111,
        cryptoAddresses: null,
        variantTypes: [],
        variants: collection([]),
        properties: [{ id: "coop-harbor-ether-lantern-prop", key: "mount", value: "desktop" }],
        image: image("coop-product-harbor-ether-lantern", "Harbor Ether Lantern"),
        company: companies[2],
    },
] satisfies FixtureProduct[];

const jobs = [
    {
        id: "coop-job-dock-foreman",
        title: "Dock Foreman",
        description: "Coordinate cooperative freight and loading",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: true,
        url: "/jobs/dock-foreman",
        positions: 1,
        salaryRange: { min: 3400, max: 4200, currency: "USD" },
        employmentType: "full_time",
        applyUrl: "https://helix.example/apply/dock-foreman",
        location: "North Port",
        bounty: { amount: 1600, currency: "USD" },
        company: companies[0],
        createdBy: identities[0],
        allowedIdentities: [identities[0], identities[2]],
        disallowedIdentities: [identities[1]],
        cryptoAddresses: [{ chain: "solana", address: "SoDockForeman630" }],
        image: image("coop-job-dock-foreman", "Dock Foreman"),
    },
    {
        id: "coop-job-product-steward",
        title: "Product Steward",
        description: "Shape the cooperative product line",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: false,
        url: "/jobs/product-steward",
        positions: 2,
        salaryRange: { min: 4700, max: 5400, currency: "USD" },
        employmentType: "contract",
        applyUrl: "https://salt.example/apply/product-steward",
        location: "Remote",
        bounty: { amount: 1900, currency: "USD" },
        company: companies[1],
        createdBy: identities[1],
        allowedIdentities: [identities[1]],
        disallowedIdentities: [identities[0]],
        cryptoAddresses: [{ chain: "ethereum", address: "0xSteward640" }],
        image: image("coop-job-product-steward", "Product Steward"),
    },
] satisfies FixtureJob[];

const startups = [
    {
        id: "coop-startup-reef-signal",
        title: "Reef Signal",
        description: "Signals for better shipment handoff",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: true,
        stage: "mvp",
        location: "Harbor",
        lookingFor: ["founders"],
        alreadyHave: ["product"],
        fundsNeeded: { amount: 30000, currency: "USD" },
        applyUrl: "https://reef.example/apply",
        company: companies[0],
        createdBy: identities[0],
        involvedUsers: [identities[0], identities[2]],
        cryptoAddresses: [{ chain: "solana", address: "SoReefSignal650" }],
        image: image("coop-startup-reef-signal", "Reef Signal"),
    },
    {
        id: "coop-startup-salt-bridge",
        title: "Salt Bridge",
        description: "Bridge software for the co-op",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: false,
        stage: "early",
        location: "Distributed",
        lookingFor: ["distribution"],
        alreadyHave: ["team"],
        fundsNeeded: { amount: 18000, currency: "USD" },
        applyUrl: "https://salt.example/apply",
        company: companies[1],
        createdBy: identities[1],
        involvedUsers: [identities[1]],
        cryptoAddresses: [{ chain: "tron", address: "TSaltBridge660" }],
        image: image("coop-startup-salt-bridge", "Salt Bridge"),
    },
] satisfies FixtureStartup[];

const posts = [
    {
        id: "coop-post-coop-logistics-roundup",
        title: "Co-op Logistics Roundup",
        slug: "coop-logistics-roundup",
        description: "Weekly logistics changes from the co-op server",
        content: "The co-op server shipped better handoffs, clearer routing, and a more visible publishing flow.",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: true,
        company: companies[0],
        heroImage: image("coop-post-coop-logistics-roundup", "Co-op Logistics Roundup"),
        meta: {
            title: "Co-op Logistics Roundup",
            description: "Weekly logistics changes from the co-op server",
            image: image("coop-post-coop-logistics-roundup-meta", "Co-op Logistics Roundup meta"),
        },
        categories: [{ id: "coop-category-announcements", title: "Announcements", slug: "announcements" }],
        populatedAuthors: [
            {
                id: identities[0].id,
                nickname: identities[0].name,
                image: identities[0].image,
            },
        ],
        createdBy: { id: identities[0].id, name: identities[0].name, email: identities[0].email },
        hasLiked: false,
        likeCount: 9,
        publishedAt: "2025-03-05T09:00:00.000Z",
        createdAt: "2025-03-04T09:00:00.000Z",
        updatedAt: "2025-03-05T09:15:00.000Z",
        contentRankScore: 170,
    },
    {
        id: "coop-post-field-notes",
        title: "Field Notes",
        slug: "field-notes",
        description: "A lighter note from the field",
        content: "Field notes focused on smaller operational improvements and a calmer publishing cadence.",
        serverURL: COOP_SYNDICATION_URL,
        _status: "published",
        isSubscribed: false,
        company: companies[1],
        heroImage: image("coop-post-field-notes", "Field Notes"),
        meta: {
            title: "Field Notes",
            description: "A lighter note from the field",
            image: image("coop-post-field-notes-meta", "Field Notes meta"),
        },
        categories: [{ id: "coop-category-field-notes", title: "Field Notes", slug: "field-notes" }],
        populatedAuthors: [
            {
                id: identities[1].id,
                nickname: identities[1].name,
                image: identities[1].image,
            },
        ],
        createdBy: { id: identities[1].id, name: identities[1].name, email: identities[1].email },
        hasLiked: true,
        likeCount: 4,
        publishedAt: "2025-03-06T09:00:00.000Z",
        createdAt: "2025-03-05T09:00:00.000Z",
        updatedAt: "2025-03-06T09:15:00.000Z",
        contentRankScore: 80,
    },
] satisfies FixturePost[];

const comments = [
    {
        id: "coop-comment-company-helix",
        content: "Helix Harbor keeps things moving.",
        company: companies[0],
        createdBy: identities[2],
        anonymousHash: "coop-anon-helix",
        replyPostRelationTo: "companies",
        replyPostValue: companies[0].id,
        serverUrl: COOP_SYNDICATION_URL,
        createdAt: "2025-03-03T10:00:00.000Z",
        updatedAt: "2025-03-03T10:00:00.000Z",
    },
    {
        id: "coop-comment-job-dock-foreman",
        content: "Dock Foreman keeps Helix Harbor moving.",
        company: companies[0],
        createdBy: identities[1],
        anonymousHash: "coop-anon-dock-foreman",
        replyPostRelationTo: "jobs",
        replyPostValue: jobs[0].id,
        serverUrl: COOP_SYNDICATION_URL,
        createdAt: "2025-03-03T11:00:00.000Z",
        updatedAt: "2025-03-03T11:00:00.000Z",
    },
    {
        id: "coop-comment-startup-reef",
        content: "Reef Signal is worth watching.",
        company: companies[0],
        createdBy: identities[0],
        anonymousHash: "coop-anon-reef",
        replyPostRelationTo: "startups",
        replyPostValue: startups[0].id,
        serverUrl: COOP_SYNDICATION_URL,
        createdAt: "2025-03-04T10:00:00.000Z",
        updatedAt: "2025-03-04T10:00:00.000Z",
    },
] satisfies FixtureComment[];

const syndications = [
    {
        id: "coop-syndication-main",
        name: "Co-op Main",
        description: "Primary cooperative syndicated content source",
        url: COOP_SYNDICATION_URL,
        enabled: true,
    },
] satisfies FixtureSyndication[];

const carts = [
    {
        id: "coop-cart-alpha",
        secret: "coop-alpha-secret",
        status: "pending",
        currency: "USD",
        subtotal: 213,
        createdAt: "2025-03-01T09:00:00.000Z",
        updatedAt: "2025-03-01T10:00:00.000Z",
        purchasedAt: null,
        customer: { id: identities[1].id, name: identities[1].name, email: identities[1].email },
        items: [
            { id: "coop-cart-alpha-item-1", quantity: 3, product: products[2] },
            { id: "coop-cart-alpha-item-2", quantity: 1, product: products[1] },
        ],
    },
    {
        id: "coop-cart-anon-shopping",
        secret: "anon-shopping-coop-secret",
        status: "pending",
        currency: "USD",
        subtotal: 213,
        createdAt: "2025-04-01T09:00:00.000Z",
        updatedAt: "2025-04-01T09:00:00.000Z",
        purchasedAt: null,
        customer: null,
        items: [
            { id: "coop-cart-anon-shopping-item-1", quantity: 3, product: products[2] },
            { id: "coop-cart-anon-shopping-item-2", quantity: 1, product: products[1] },
        ],
    },
] satisfies FixtureCart[];

const orders = [
    {
        id: "coop-order-alpha",
        status: "paid",
        payerAddress: "SoCoopOrder1717",
        customer: { id: identities[1].id },
        transactions: [{ id: "coop-tx-1" }],
        cryptoPrices: [
            {
                id: "coop-crypto-price-1",
                chain: "solana",
                stablePerNative: 25,
                nativePerStable: 0.04,
                expectedNativeAmount: "3.200000000",
                fetchedAt: "2025-03-10T12:00:00.000Z",
            },
        ],
        transactionHashes: [
            {
                id: "coop-hash-1",
                chain: "solana",
                transactionHash: "coop-solana-tx-1",
                product: { id: products[0].id },
            },
        ],
        currency: "USD",
        amount: 164,
        customerEmail: identities[1].email,
        createdAt: "2025-03-10T12:00:00.000Z",
        updatedAt: "2025-03-10T12:05:00.000Z",
        items: [
            {
                id: "coop-order-item-1",
                quantity: 2,
                product: {
                    id: products[0].id,
                    serverURL: products[0].serverURL,
                    name: products[0].name,
                    priceInETH: products[0].priceInETH,
                    priceInSOL: products[0].priceInSOL,
                    priceInTRX: products[0].priceInTRX,
                    cryptoAddresses: products[0].cryptoAddresses,
                    company: { id: companies[0].id, cryptoAddresses: companies[0].cryptoAddresses },
                },
            },
        ],
        shippingAddress: {
            title: "Depot",
            firstName: "Luca",
            lastName: "Vale",
            company: "Helix Harbor",
            addressLine1: "18 Bridge Road",
            addressLine2: "",
            city: "North Port",
            postalCode: "22000",
            state: "Coast",
            country: "Liberland",
            phone: "+1 555 0606",
        },
    },
] satisfies FixtureOrder[];

const meUser = {
    user: {
        id: "coop-user-iris",
        name: "Iris Shore",
        email: "iris@example.test",
        phone: "+1 555 0600",
        shippingAddress: {
            title: "Depot",
            firstName: "Iris",
            lastName: "Shore",
            company: "Helix Harbor",
            addressLine1: "8 Dockside Lane",
            addressLine2: "Unit 3",
            city: "North Port",
            state: "Coast",
            postalCode: "22001",
            country: "Liberland",
            phone: "+1 555 0601",
        },
        wallets: [{ chain: "solana", provider: "phantom", address: "SoCoopWallet606" }],
    },
} satisfies FixtureMeUser;

export const coopFixtures: GraphQLFixtureBundle = {
    identities,
    companies,
    products,
    jobs,
    startups,
    posts,
    comments,
    syndications,
    carts,
    orders,
    meUser,
};
