export type MockNode = {
    __typename?: string;
    id?: string;
    name?: string | null;
    title?: string | null;
    description?: string | null;
    slug?: string | null;
    serverURL?: string | null;
    serverUrl?: string | null;
    _status?: string | null;
    website?: string | null;
    phone?: string | null;
    email?: string | null;
    content?: string | null;
    anonymousHash?: string | null;
    hasLiked?: boolean | null;
    likeCount?: number | null;
    replyPostRelationTo?: string | null;
    replyPostValue?: string | null;
    currency?: string | null;
    secret?: string | null;
    subtotal?: number | null;
    status?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    priceInUSDEnabled?: boolean | null;
    priceInUSD?: number | null;
    priceInETH?: number | null;
    priceInSOL?: number | null;
    priceInTRX?: number | null;
    inventory?: number | null;
    enableVariants?: boolean | null;
    orderable?: boolean | null;
    companyIdentityId?: string | null;
    url?: string | null;
    applyUrl?: string | null;
    salaryRange?: MockNode | null;
    positions?: number | null;
    alreadyHave?: string[];
    location?: string | null;
    employmentType?: string | null;
    stage?: string | null;
    lookingFor?: string[];
    itemCount?: number;
    amount?: number | null;
    quantity?: number;
    purchasedAt?: string | null;
    payerAddress?: string | null;
    chain?: string | null;
    address?: string | null;
    value?: string | MockNode | null;
    label?: string | null;
    key?: string | null;
    mimeType?: string | null;
    filename?: string | null;
    width?: number | null;
    height?: number | null;
    alt?: string | null;
    publishedAt?: string | null;
    contentRankScore?: number;
    isSubscribed?: boolean | null;
    isActive?: boolean | null;
    success?: boolean | null;
    limit?: number | null;
    page?: number | null;
    totalDocs?: number | null;
    totalPages?: number | null;
    hasNextPage?: boolean | null;
    hasPrevPage?: boolean | null;
    nextPage?: number | null;
    prevPage?: number | null;
    targetCollection?: string | null;
    targetID?: string | null;
    distinctId?: string | null;
    eventId?: string | null;
    sessionId?: string | null;
    transactionHash?: string | null;
    nativePerStable?: number | null;
    stablePerNative?: number | null;
    expectedNativeAmount?: string | null;
    fetchedAt?: string | null;
    priority?: number;
    postedAt?: string | null;
    relationTo?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    provider?: string | null;
    message?: string | null;
    allowedIdentities?: MockNode[];
    disallowedIdentities?: MockNode[];
    cryptoAddresses?: MockNode[];
    docs?: MockNode[];
    involvedUsers?: MockNode[];
    items?: MockNode[];
    categories?: MockNode[];
    populatedAuthors?: MockNode[];
    relatedPosts?: MockNode[];
    options?: MockNode[];
    properties?: MockNode[];
    transactions?: MockNode[];
    transactionHashes?: MockNode[];
    variantTypes?: MockNode[];
    variants?: MockCollection;
    wallets?: MockNode[];
    image?: MockNode | null;
    heroImage?: MockNode | null;
    meta?: MockNode | null;
    company?: MockNode | null;
    identity?: MockNode | null;
    createdBy?: MockNode | null;
    user?: MockNode | null;
    customer?: MockNode | null;
    product?: MockNode | null;
    startup?: MockNode | null;
    job?: MockNode | null;
    doc?: MockNode | null;
    replyComment?: MockNode | null;
    replyPost?: MockNode | null;
    variant?: MockNode | null;
    variantType?: MockNode | null;
    shippingAddress?: MockNode | null;
    bounty?: MockNode | null;
    fundsNeeded?: MockNode | null;
    cryptoPrices?: MockNode[];
    analytics?: MockNode | null;
};

export type MockCollection<T = MockNode> = {
    docs: T[];
    totalDocs: number;
    limit: number;
    totalPages: number;
    page: number;
    hasPrevPage: boolean;
    hasNextPage: boolean;
    prevPage: number | null;
    nextPage: number | null;
};

export type GraphQLFixtureBundle = {
    identities: MockNode[];
    companies: MockNode[];
    products: MockNode[];
    jobs: MockNode[];
    startups: MockNode[];
    posts: MockNode[];
    comments: MockNode[];
    syndications: MockNode[];
    carts: MockNode[];
    orders: MockNode[];
    meUser: MockNode;
};

export type GraphQLRequestLog = {
    timestamp: string;
    method: "OPTIONS" | "POST";
    url: string;
    host: string;
    operationName?: string;
    requestBody?: Record<string, unknown>;
    responseStatusCode: number;
    responseBody?: Record<string, unknown>;
    alias?: string;
};

export type GraphQLRequestLogPayload = {
    specRelative: string;
    logs: GraphQLRequestLog[];
};
