export type MockNode = {
    [key: string]: unknown;
    __typename?: string;
    id?: string;
    name?: string | null;
    title?: string | null;
    description?: string | null;
    slug?: string | null;
    serverURL?: string | null;
    serverUrl?: string | null;
    _status?: string | null;
    website?: string | null;
    phone?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    content?: string | null;
    anonymousHash?: string | null;
    hasLiked?: boolean | null;
    likeCount?: number | null;
    replyPostRelationTo?: string | null;
    replyPostValue?: string | null;
    currency?: string | null;
    secret?: string | null;
    subtotal?: number | null;
    status?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    priceInUSDEnabled?: boolean | null;
    priceInUSD?: number | null;
    priceInETH?: string | number | null;
    priceInSOL?: string | number | null;
    priceInTRX?: string | number | null;
    inventory?: number | null;
    enableVariants?: boolean | null;
    orderable?: boolean | null;
    companyIdentityId?: string | null;
    url?: string | null;
    applyUrl?: string | null;
    salaryRange?: MockNode | null;
    positions?: number | null;
    alreadyHave?: string[] | null;
    location?: string | null;
    employmentType?: string | null;
    stage?: string | null;
    lookingFor?: string[] | null;
    itemCount?: number | null;
    amount?: number | null;
    quantity?: number | null;
    purchasedAt?: string | null;
    payerAddress?: string | null;
    chain?: string | null;
    address?: string | null;
    value?: string | MockNode | null;
    label?: string | null;
    key?: string | null;
    mimeType?: string | null;
    filename?: string | null;
    width?: number | null;
    height?: number | null;
    alt?: string | null;
    publishedAt?: string | null;
    contentRankScore?: number | null;
    isSubscribed?: boolean | null;
    isActive?: boolean | null;
    success?: boolean | null;
    limit?: number | null;
    page?: number | null;
    totalDocs?: number | null;
    totalPages?: number | null;
    hasNextPage?: boolean | null;
    hasPrevPage?: boolean | null;
    nextPage?: number | null;
    prevPage?: number | null;
    targetCollection?: string | null;
    targetID?: string | null;
    distinctId?: string | null;
    eventId?: string | null;
    sessionId?: string | null;
    transactionHash?: string | null;
    nativePerStable?: number | null;
    stablePerNative?: number | null;
    expectedNativeAmount?: string | null;
    fetchedAt?: string | null;
    priority?: number;
    postedAt?: string | null;
    relationTo?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    provider?: string | null;
    message?: string | null;
    allowedIdentities?: Array<Record<string, unknown> | MockNode> | null;
    disallowedIdentities?: Array<Record<string, unknown> | MockNode> | null;
    cryptoAddresses?: Record<string, unknown> | Array<Record<string, unknown> | MockNode> | null;
    docs?: Array<Record<string, unknown> | MockNode> | null;
    involvedUsers?: Array<Record<string, unknown> | MockNode> | null;
    items?: Array<Record<string, unknown> | MockNode> | null;
    categories?: Array<Record<string, unknown> | MockNode> | null;
    populatedAuthors?: Array<Record<string, unknown> | MockNode> | null;
    relatedPosts?: Array<Record<string, unknown> | MockNode> | null;
    options?: Array<Record<string, unknown> | MockNode> | null;
    properties?: Array<Record<string, unknown> | MockNode> | null;
    transactions?: Array<Record<string, unknown> | MockNode> | null;
    transactionHashes?: Array<Record<string, unknown> | MockNode> | null;
    variantTypes?: Array<Record<string, unknown> | MockNode> | null;
    variants?: Record<string, unknown> | MockCollection | null;
    wallets?: Array<Record<string, unknown> | MockNode> | null;
    image?: string | Record<string, unknown> | MockNode | null;
    heroImage?: Record<string, unknown> | MockNode | null;
    meta?: Record<string, unknown> | MockNode | null;
    company?: Record<string, unknown> | MockNode | null;
    identity?: string | Record<string, unknown> | MockNode | null;
    createdBy?: Record<string, unknown> | MockNode | null;
    user?: Record<string, unknown> | MockNode | null;
    customer?: Record<string, unknown> | MockNode | null;
    product?: Record<string, unknown> | MockNode | null;
    startup?: Record<string, unknown> | MockNode | null;
    job?: Record<string, unknown> | MockNode | null;
    doc?: Record<string, unknown> | MockNode | null;
    replyComment?: Record<string, unknown> | MockNode | null;
    replyPost?: Record<string, unknown> | MockNode | null;
    variant?: Record<string, unknown> | MockNode | null;
    variantType?: Record<string, unknown> | MockNode | null;
    shippingAddress?: Record<string, unknown> | MockNode | null;
    bounty?: Record<string, unknown> | MockNode | null;
    fundsNeeded?: Record<string, unknown> | MockNode | null;
    cryptoPrices?: Array<Record<string, unknown> | MockNode> | null;
    analytics?: Record<string, unknown> | MockNode | null;
};

export type MockCollection<T = MockNode> = {
    docs: T[];
    totalDocs: number;
    limit: number;
    totalPages: number;
    page: number;
    hasPrevPage: boolean;
    hasNextPage: boolean;
    prevPage: number | null;
    nextPage: number | null;
};

export type GraphQLFixtureBundle = {
    identities: MockNode[];
    companies: MockNode[];
    products: MockNode[];
    jobs: MockNode[];
    startups: MockNode[];
    posts: MockNode[];
    comments: MockNode[];
    syndications: MockNode[];
    carts: MockNode[];
    orders: MockNode[];
    meUser: MockNode;
};

export type GraphQLRequestLog = {
    timestamp: string;
    method: "OPTIONS" | "POST";
    url: string;
    host: string;
    operationName?: string;
    requestBody?: Record<string, unknown>;
    responseStatusCode: number;
    responseBody?: Record<string, unknown>;
    alias?: string;
};

export type GraphQLRequestLogPayload = {
    specRelative: string;
    logs: GraphQLRequestLog[];
};
