export type MockNode = {
    id?: string;
    name?: string;
    title?: string;
    description?: string;
    slug?: string;
    serverURL?: string;
    _status?: string;
    website?: string;
    phone?: string;
    email?: string;
    content?: string;
    anonymousHash?: string;
    replyPostRelationTo?: string;
    replyPostValue?: string;
    currency?: string;
    secret?: string;
    subtotal?: number;
    status?: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string | null;
    priceInUSDEnabled?: boolean;
    priceInUSD?: number | null;
    priceInETH?: number | null;
    priceInSOL?: number | null;
    priceInTRX?: number | null;
    inventory?: number | null;
    enableVariants?: boolean;
    orderable?: boolean;
    companyIdentityId?: string;
    url?: string;
    applyUrl?: string;
    salaryRange?: MockNode | null;
    positions?: number | null;
    alreadyHave?: string[];
    location?: string;
    employmentType?: string;
    stage?: string;
    lookingFor?: string[];
    itemCount?: number;
    amount?: number | null;
    quantity?: number;
    purchasedAt?: string | null;
    payerAddress?: string;
    chain?: string;
    address?: string;
    value?: string | MockNode | null;
    label?: string;
    key?: string;
    mimeType?: string;
    filename?: string;
    width?: number;
    height?: number;
    alt?: string;
    publishedAt?: string;
    contentRankScore?: number;
    isSubscribed?: boolean;
    isActive?: boolean;
    success?: boolean;
    limit?: number;
    page?: number;
    totalDocs?: number;
    totalPages?: number;
    hasNextPage?: boolean;
    hasPrevPage?: boolean;
    nextPage?: number | null;
    prevPage?: number | null;
    targetCollection?: string;
    targetID?: string;
    distinctId?: string;
    eventId?: string;
    sessionId?: string;
    transactionHash?: string;
    nativePerStable?: number | null;
    stablePerNative?: number | null;
    expectedNativeAmount?: string | null;
    fetchedAt?: string;
    priority?: number;
    postedAt?: string;
    relationTo?: string;
    firstName?: string;
    lastName?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
    addressLine1?: string;
    addressLine2?: string;
    provider?: string;
    message?: string;
    allowedIdentities?: MockNode[];
    disallowedIdentities?: MockNode[];
    cryptoAddresses?: MockNode[];
    docs?: MockNode[];
    involvedUsers?: MockNode[];
    items?: MockNode[];
    categories?: MockNode[];
    populatedAuthors?: MockNode[];
    options?: MockNode[];
    properties?: MockNode[];
    transactions?: MockNode[];
    transactionHashes?: MockNode[];
    variantTypes?: MockNode[];
    variants?: MockCollection;
    wallets?: MockNode[];
    image?: MockNode | null;
    heroImage?: MockNode | null;
    meta?: MockNode | null;
    company?: MockNode | null;
    identity?: MockNode | null;
    createdBy?: MockNode | null;
    user?: MockNode | null;
    customer?: MockNode | null;
    product?: MockNode | null;
    startup?: MockNode | null;
    job?: MockNode | null;
    doc?: MockNode | null;
    replyComment?: MockNode | null;
    replyPost?: MockNode | null;
    variant?: MockNode | null;
    variantType?: MockNode | null;
    shippingAddress?: MockNode | null;
    bounty?: MockNode | null;
    fundsNeeded?: MockNode | null;
    cryptoPrices?: MockNode[];
    analytics?: MockNode | null;
};

export type MockCollection = {
    docs: MockNode[];
    totalDocs: number;
    limit: number;
    totalPages: number;
    page: number;
    hasPrevPage: boolean;
    hasNextPage: boolean;
    prevPage: number | null;
    nextPage: number | null;
};

export type GraphQLFixtureBundle = {
    identities: MockNode[];
    companies: MockNode[];
    products: MockNode[];
    jobs: MockNode[];
    startups: MockNode[];
    posts: MockNode[];
    comments: MockNode[];
    syndications: MockNode[];
    carts: MockNode[];
    orders: MockNode[];
    meUser: MockNode;
};

export type GraphQLRequestLog = {
    timestamp: string;
    method: "OPTIONS" | "POST";
    url: string;
    host: string;
    operationName?: string;
    requestBody?: Record<string, unknown>;
    responseStatusCode: number;
    responseBody?: Record<string, unknown>;
    alias?: string;
};

export type GraphQLRequestLogPayload = {
    specRelative: string;
    logs: GraphQLRequestLog[];
};
