import { image, collection, COOP_SYNDICATION_URL } from "../fixtures/shared";
import { companies } from "./companies";
import { identities } from "./identities";
import { Product__Status, Product_CryptoAddresses_Chain } from "../../../../src/generated/graphql";
import type { Product } from "../../../../src/generated/graphql";

export const products: Product[] = [
    {
        id: "coop-product-lighthouse-kit",
        name: "Lighthouse Kit",
        description: "Unlimited navigation hardware",
        serverURL: COOP_SYNDICATION_URL,
        _status: Product__Status.Published,
        isSubscribed: true,
        url: "/products/lighthouse-kit",
        inventory: null,
        orderable: true,
        enableVariants: false,
        companyIdentityId: identities[0].id,
        priceInUSDEnabled: true,
        priceInUSD: 64,
        priceInETH: "0.027",
        priceInSOL: "1.1",
        priceInTRX: "141",
        cryptoAddresses: { chain: Product_CryptoAddresses_Chain.Solana, address: "SoLight620" },
        variantTypes: [],
        variants: collection([]),
        properties: [{ id: "coop-product-prop-1", key: "finish", value: "matte" }],
        image: image("coop-product-lighthouse-kit", "Lighthouse Kit"),
        company: companies[0],
    },
    {
        id: "coop-product-tide-lamp",
        name: "Tide Lamp",
        description: "Limited batch desk lamp",
        serverURL: COOP_SYNDICATION_URL,
        _status: Product__Status.Published,
        isSubscribed: false,
        url: "/products/tide-lamp",
        inventory: 5,
        orderable: true,
        enableVariants: true,
        companyIdentityId: identities[1].id,
        priceInUSDEnabled: true,
        priceInUSD: 99,
        priceInETH: "0.041",
        priceInSOL: "1.7",
        priceInTRX: "208",
        cryptoAddresses: { chain: Product_CryptoAddresses_Chain.Tron, address: "TTide630" },
        variantTypes: [{ id: "coop-variant-size", name: "size", label: "Size" }],
        variants: collection([
            {
                id: "coop-tide-lamp-mini",
                title: "Mini",
                inventory: 2,
                priceInUSDEnabled: true,
                priceInUSD: 89,
                options: [
                    {
                        id: "coop-tide-lamp-mini-size",
                        label: "Size",
                        value: "Mini",
                        variantType: { id: "coop-variant-size", name: "size", label: "Size" },
                    },
                ],
            },
        ]),
        properties: [{ id: "coop-product-prop-2", key: "theme", value: "dawn" }],
        image: image("coop-product-tide-lamp", "Tide Lamp"),
        company: companies[1],
    },
    {
        id: "coop-product-harbor-ether-lantern",
        name: "Harbor Ether Lantern",
        description: "Ethereum product from the co-op server",
        serverURL: COOP_SYNDICATION_URL,
        _status: Product__Status.Published,
        isSubscribed: false,
        url: "/products/harbor-ether-lantern",
        inventory: 3,
        orderable: true,
        enableVariants: false,
        companyIdentityId: identities[0].id,
        priceInUSDEnabled: true,
        priceInUSD: 38,
        priceInETH: "0.041",
        priceInSOL: "0.9",
        priceInTRX: "111",
        cryptoAddresses: null,
        variantTypes: [],
        variants: collection([]),
        properties: [{ id: "coop-harbor-ether-lantern-prop", key: "mount", value: "desktop" }],
        image: image("coop-product-harbor-ether-lantern", "Harbor Ether Lantern"),
        company: companies[2],
    },
];
