export {
    CloverWalletAdapter,
    Coin98WalletAdapter,
    HyperPayWalletAdapter,
    LedgerWalletAdapter,
    MathWalletAdapter,
    PhantomWalletAdapter,
    SafePalWalletAdapter,
    SkyWalletAdapter,
    SolflareWalletAdapter,
    TokenPocketWalletAdapter,
    TorusWalletAdapter,
    TrustWalletAdapter,
    XDEFIWalletAdapter,
} from "@solana/wallet-adapter-wallets";
